### ISSUE TITLE
How to verify the validity of access credentials?

### ISSUE THREAD

**Issue by VJalili** [CloudVE/cloudbridge#120]
What is the recommended approach for access credentials verification?

**Comment by nuwang** [comment]
The best way is to simply initialize the provider with the given credentials, then call the provider.authenticate() method, which is intended for that very purpose.
https://github.com/gvlproject/cloudbridge/blob/23fc4b0297566451b3fc4c28924c87c26bf3ff9d/cloudbridge/cloud/interfaces/provider.py#L58

**Comment by VJalili** [comment]
The function `authenticate` works fine when _invalid_ credentials are provided. For instance, when using AWS, the following  configuration can trigger `ProviderConnectionException` exception.

```python
config = {'aws_access_key': 'AAB'),  # while the correct key is 'AAA'
          'aws_secret_key': 'BBB'}
connection = CloudProviderFactory().create_provider(ProviderList.AWS, config)
try:
    if connection.authenticate():
        print 'voila!'
except ProviderConnectionException as e:
    print 'invalid credentials'
```

However, if one the keys is `None`, `authenticate` can trigger `URLError`. For instance, the following config triggers `URLError` error when `authenticate` function is called with the following traceback.

```python
config = {'aws_access_key': None), 
          'aws_secret_key': 'BBB'}
```

```shell
Traceback (most recent call last):
  File "/.venv/lib/python2.7/site-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
```

I can check for `None` value when receiving credentials from a user, and handle this exception differently. However, IMHO it would be better if cloudbridge captures such corner cases and throws a unified exception instead.

**Comment by nuwang** [comment]
@VJalili Currently, authentication failures are caught in a generic catch block:
https://github.com/gvlproject/cloudbridge/blob/eb20e3d88f2893a6e281ceead7ab8fd3527be6af/cloudbridge/cloud/base/provider.py#L105

So all errors should be caught. Is this originating from a different line perhaps? Maybe the create_provider call?

**Comment by VJalili** [comment]
This is a full stack trace. The error is originating from boto, so that might be a hint to trace this back.

Also, you're right, that generic exception should catch all these; though it is weird why it is not. Are you able to reproduce this error?

**Comment by nuwang** [comment]
@VJalili I can't recreate it.

Here's the code I ran:
```
from cloudbridge.cloud.factory import CloudProviderFactory
from cloudbridge.cloud.factory import ProviderList
from cloudbridge.cloud.interfaces.exceptions import ProviderConnectionException

config = {'aws_access_key': None,  # while the correct key is 'AAA'
          'aws_secret_key': 'BBB'}
connection = CloudProviderFactory().create_provider(ProviderList.AWS, config)
try:
    if connection.authenticate():
        print('voila!')
    else:
        print('oops')
except ProviderConnectionException as e:
    print('invalid credentials')
```

Here's the result:
```
ERROR:cloudbridge.cloud.base.provider:ProviderConnectionException occurred
Traceback (most recent call last):
  1 from cloudbridge.cloud.factory import CloudProviderFactory
  File "/Users/Nuwan/work/cloudbridge/cloudbridge/cloud/base/provider.py", line 103, in authenticate
    self.security.key_pairs.list()
  File "/Users/Nuwan/work/cloudbridge/cloudbridge/cloud/providers/aws/services.py", line 87, in list
    return self.svc.list(limit=limit, marker=marker)
  File "/Users/Nuwan/work/cloudbridge/cloudbridge/cloud/providers/aws/helpers.py", line 219, in list
    results = [self.cb_resource(self.provider, obj) for obj in boto_objs]
  File "/Users/Nuwan/work/cloudbridge/cloudbridge/cloud/providers/aws/helpers.py", line 219, in <listcomp>
    results = [self.cb_resource(self.provider, obj) for obj in boto_objs]
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/boto3/resources/collection.py", line 161, in pages
    pages = [getattr(client, self._py_operation_name)(**params)]
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/client.py", line 602, in _make_api_call
    operation_model, request_dict)
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 168, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 152, in create_request
    operation_name=operation_model.name)
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/signers.py", line 154, in sign
    auth.add_auth(request)
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/auth.py", line 366, in add_auth
    self._inject_signature_to_request(request, signature)
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/auth.py", line 369, in _inject_signature_to_request
    l = ['AWS4-HMAC-SHA256 Credential=%s' % self.scope(request)]
  File "/Users/Nuwan/work/cloudbridge/venv/lib/python3.6/site-packages/botocore/auth.py", line 319, in scope
    return '/'.join(scope)
TypeError: sequence item 0: expected str instance, NoneType found
invalid credential
```

It seems to correctly catch the error. Something that's unusual is that the stack trace you provided contains no classes from cloudbridge. It must be a partial trace if no cloudbridge classes are connected.

**Comment by VJalili** [comment]
Interesting! would it be the cloudbridge version? I'm using current latest release, i.e., 0.3.3. 

And here is how I check user authentication in Galaxy: 

https://github.com/VJalili/galaxy/blob/70b669992b10682d45c519ef885667ddf52f381c/lib/galaxy/managers/cloud.py#L78-L82

It looks quite similar to your approach; so, not sure what is causing the issue on my end.

**Comment by nuwang** [comment]
Can you try running the snipper I provided within galaxy's virtualenv and check the stack trace?

**Comment by VJalili** [comment]
I get `invalid credentials` as you're getting. So, I guess there should be an error somewhere in that branch.

**Comment by nuwang** [comment]
@VJalili I take it we can close this?

**Comment by VJalili** [comment]
@nuwang I'm capturing `None` credentials before passing them cloudbridge; hence, I can capture/prevent the discussed issue. However, I think it would be better if cloudbridge can catch cases where credentials are `None`. 

For now, I think we can close this issue.
