### ISSUE TITLE
Sporadic error launching on GCP

### ISSUE THREAD

**Issue by nuwang** [CloudVE/cloudbridge#225]
```
[2019-10-22 16:15:07,099: ERROR/ForkPoolWorker-6] Task cloudlaunch.tasks.create_appliance[2f15eac4-7f45-42b5-af57-4f2b4b3b49bf] raised unexpected: Exception("Create appliance task failed: 'NoneType' object has no attribute 'parameters'",)
Traceback (most recent call last):
  File "/app/django-cloudlaunch/cloudlaunch/tasks.py", line 88, in create_appliance
    provider_config)
  File "/app/django-cloudlaunch/cloudlaunch/backend_plugins/simple_web_app.py", line 55, in deploy
    name, task, app_config, provider_config)
  File "/app/django-cloudlaunch/cloudlaunch/backend_plugins/base_vm_app.py", line 307, in deploy
    provider_config)
  File "/app/django-cloudlaunch/cloudlaunch/backend_plugins/cloudman2_app.py", line 160, in _provision_host
    return super()._provision_host(name, task, app_config, provider_config)
  File "/app/django-cloudlaunch/cloudlaunch/backend_plugins/base_vm_app.py", line 341, in _provision_host
    provider, cloudlaunch_config)
  File "/app/django-cloudlaunch/cloudlaunch/backend_plugins/base_vm_app.py", line 268, in _resolve_launch_properties
    subnet = self._setup_networking(provider, net_id, subnet_id, placement)
  File "/app/django-cloudlaunch/cloudlaunch/backend_plugins/base_vm_app.py", line 221, in _setup_networking
    provider, net_id, placement)
  File "/app/django-cloudlaunch/cloudlaunch/backend_plugins/base_vm_app.py", line 211, in _get_or_create_default_subnet
    sn = provider.networking.subnets.get_or_create_default()
  File "/app/venv/lib/python3.6/site-packages/cloudbridge/providers/gcp/services.py", line 1056, in get_or_create_default
    if sn.region_name == region_name:
  File "/app/venv/lib/python3.6/site-packages/cloudbridge/providers/gcp/resources.py", line 1580, in region_name
    return parsed_url.parameters['region']
AttributeError: 'NoneType' object has no attribute 'parameters'
```

**Comment by nuwang** [comment]
This has been fixed with: https://github.com/CloudVE/cloudbridge/commit/9b0569fba7ecf7459c96e9dcf948c769954410ac
